id: P010487
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 20:52:20.701348
source_metadata:
  id: bdr:W1KG13160
  title: མན་ངག་རིན་པོ་ཆེ་སྤུངས་པ།
  author: ''
  volumes:
    509c5152d52646a4b2162b86c22c12e9:
      image_group_id: I1KG13439
      title: ''
      volume_number: 1
      total_pages: 320
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
