id: I5905A054
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T06:43:09+00:00'
last_modified: '2022-06-08T13:57:48.286127+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13160
  title: མན་ངག་རིན་པོ་ཆེ་སྤུངས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4044':
      image_group_id: I1KG13439
      title: ''
      total_pages: 320
      order: 1
      base_file: 4044.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
